### PR TITLE
ValidatedMethod -> Method

### PR DESCRIPTION
**Pull request by SachaG**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/validated-method/pull/14%23issuecomment-162416115%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/14%23issuecomment-162417641%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/14%23issuecomment-162575484%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/validated-method/pull/14%23issuecomment-162416115%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22We%20renamed%20it%20in%200.2.0%20based%20on%20feedback%20from%20the%20forums.%20See%20the%20change%20log.%22%2C%20%22created_at%22%3A%20%222015-12-07T05%3A35%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22Oh%2C%20is%20it%20just%20not%20published%20to%20Atmosphere%20yet%3F%20Because%20using%20%60ValidatedMethod%60%20threw%20an%20error%20for%20me.%20%22%2C%20%22created_at%22%3A%20%222015-12-07T05%3A50%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/358832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/SachaG%22%7D%7D%2C%20%7B%22body%22%3A%20%22We%20renamed%20the%20package%20as%20well%3A%20https%3A//atmospherejs.com/mdg/validated-method%5Cr%5Cn%5Cr%5CnSince%20there%20were%203%20users%20of%20the%20original%20I%20didn%27t%20do%20any%20backcompat.%20I%20should%20maybe%20mark%20the%20old%20one%20as%20deprecated%20somehow.%22%2C%20%22created_at%22%3A%20%222015-12-07T16%3A22%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/validated-method/pull/14#issuecomment-162416115'>General Comment</a></b>
- <a href='https://github.com/stubailo'></a> We renamed it in 0.2.0 based on feedback from the forums. See the change log.
- <a href='https://github.com/SachaG'></a> Oh, is it just not published to Atmosphere yet? Because using `ValidatedMethod` threw an error for me.
- <a href='https://github.com/stubailo'></a> We renamed the package as well: https://atmospherejs.com/mdg/validated-method
  Since there were 3 users of the original I didn't do any backcompat. I should maybe mark the old one as deprecated somehow.

<a href='https://www.codereviewhub.com/meteor/validated-method/pull/14?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/validated-method/pull/14?approve=1'></a>&nbsp;<a href='https://github.com/meteor/validated-method/pull/14'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/validated-method/pull/14'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by stubailo** [comment]
We renamed it in 0.2.0 based on feedback from the forums. See the change log.

**Comment by SachaG** [comment]
Oh, is it just not published to Atmosphere yet? Because using `ValidatedMethod` threw an error for me.

**Comment by stubailo** [comment]
We renamed the package as well: https://atmospherejs.com/mdg/validated-method

Since there were 3 users of the original I didn't do any backcompat. I should maybe mark the old one as deprecated somehow.

**Pull request closed without merging**
