### PR TITLE
Add ziarno:restrict-mixin and ziarno:provide-mixin to readme

### PR DESCRIPTION
**Pull request by ziarno**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/validated-method/pull/37%23issuecomment-180319779%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/37%23issuecomment-180320539%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/37%23issuecomment-180320611%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/37%23issuecomment-180476730%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/validated-method/pull/37%23issuecomment-180319779%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40ziarno7%3A%20Thank%20you%20for%20submitting%20a%20pull%20request%21%20%20%20%20%20%20%20%20%20%20%20Before%20we%20can%20merge%20it%2C%20%20%20%20%20%20%20%20%20%20%20you%27ll%20need%20to%20sign%20the%20Meteor%20Contributor%20Agreement%20here%3A%20%20%20%20%20%20%20%20%20%20%20https%3A//contribute.meteor.com/%22%2C%20%22created_at%22%3A%20%222016-02-05T11%3A58%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4250050%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/meteor-bot%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-02-05T12%3A02%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3158482%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ziarno7%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-02-05T12%3A02%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3158482%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ziarno7%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40ziarno7%20can%20you%20sign%20the%20contributor%20agreement%2C%20please%3F%20This%20is%20just%20to%20verify%20that%20your%20work%20is%20your%20own.%22%2C%20%22created_at%22%3A%20%222016-02-05T18%3A10%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/ziarno7%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3158482%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/ziarno7'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/validated-method/pull/37#issuecomment-180319779'>General Comment</a></b>
- <a href='https://github.com/meteor-bot'></a> @ziarno7: Thank you for submitting a pull request!           Before we can merge it,           you'll need to sign the Meteor Contributor Agreement here:           https://contribute.meteor.com/
- <a href='https://github.com/ziarno7'></a> :+1:
- <a href='https://github.com/ziarno7'></a> :shipit:
- <a href='https://github.com/stubailo'></a> @ziarno7 can you sign the contributor agreement, please? This is just to verify that your work is your own.

<a href='https://www.codereviewhub.com/meteor/validated-method/pull/37?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/validated-method/pull/37?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/validated-method/pull/37?approve=0'></a>&nbsp;<a href='https://github.com/meteor/validated-method/pull/37'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/validated-method/pull/37'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by ziarno** [comment]
:+1:

**Comment by ziarno** [comment]
:shipit:

**Comment by stubailo** [comment]
@ziarno7 can you sign the contributor agreement, please? This is just to verify that your work is your own.

**Comment by stubailo** [comment]
Super belated merge! Thanks.

**Pull request merged**
