### PR TITLE
add tunifight:loggedin-mixin mixin in project readme, closes #31

### LINKED ISSUE #31: ValidatedMethod Mixin : logged-in user Mixin check before run functions
A simple Mixin to check if the user is logged in before every run function.
It requires the new `checkLoggedInError` option which includes the required informations to throw an Error.
### Github:

https://github.com/nabiltntn/loggedin-mixin
### Atmosphere:

tunifight:loggedin-mixin : https://atmospherejs.com/tunifight/loggedin-mixin

### PR DESCRIPTION
**Pull request by nabiltntn**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175198572%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175202669%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175203966%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175204095%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175290382%22%2C%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175470327%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/validated-method/pull/32%23issuecomment-175198572%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40nabiltntn%3A%20Thank%20you%20for%20submitting%20a%20pull%20request%21%20%20%20%20%20%20%20%20%20%20%20Before%20we%20can%20merge%20it%2C%20%20%20%20%20%20%20%20%20%20%20you%27ll%20need%20to%20sign%20the%20Meteor%20Contributor%20Agreement%20here%3A%20%20%20%20%20%20%20%20%20%20%20https%3A//contribute.meteor.com/%22%2C%20%22created_at%22%3A%20%222016-01-26T19%3A52%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4250050%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/meteor-bot%22%7D%7D%2C%20%7B%22body%22%3A%20%22Add%20tunifight%3Aloggedin-mixin%20mixin%20in%20project%20readme.%22%2C%20%22created_at%22%3A%20%222016-01-26T20%3A01%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/223719%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nabiltntn%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-01-26T20%3A06%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/223719%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nabiltntn%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-26T20%3A06%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/223719%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nabiltntn%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20add%20a%20link%20to%20your%20atmosphere%20page%21%22%2C%20%22created_at%22%3A%20%222016-01-26T23%3A24%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22Package%27s%20atmosphere%20page%20%5Cr%5Cnhttps%3A//atmospherejs.com/tunifight/loggedin-mixin%22%2C%20%22created_at%22%3A%20%222016-01-27T07%3A56%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/223719%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nabiltntn%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/nabiltntn%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/223719%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/nabiltntn'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/validated-method/pull/32#issuecomment-175198572'>General Comment</a></b>
- <a href='https://github.com/meteor-bot'></a> @nabiltntn: Thank you for submitting a pull request!           Before we can merge it,           you'll need to sign the Meteor Contributor Agreement here:           https://contribute.meteor.com/
- <a href='https://github.com/nabiltntn'></a> Add tunifight:loggedin-mixin mixin in project readme.
- <a href='https://github.com/nabiltntn'></a> :+1:
- <a href='https://github.com/nabiltntn'></a> :shipit:
- <a href='https://github.com/stubailo'></a> Please add a link to your atmosphere page!
- <a href='https://github.com/nabiltntn'></a> Package's atmosphere page
  https://atmospherejs.com/tunifight/loggedin-mixin

<a href='https://www.codereviewhub.com/meteor/validated-method/pull/32?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/validated-method/pull/32?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/validated-method/pull/32?approve=0'></a>&nbsp;<a href='https://github.com/meteor/validated-method/pull/32'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/validated-method/pull/32'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by nabiltntn** [comment]
Add tunifight:loggedin-mixin mixin in project readme.

**Comment by nabiltntn** [comment]
:+1:

**Comment by nabiltntn** [comment]
:shipit:

**Comment by stubailo** [comment]
Please add a link to your atmosphere page!

**Comment by nabiltntn** [comment]
Package's atmosphere page 
https://atmospherejs.com/tunifight/loggedin-mixin

**Pull request merged**
